/**
 * Helpers to detect runs that were auto-cancelled because the overall target
 * was already met (target poora ho gaya, baki pending runs cancel). Such runs
 * should be presented to the user as Completed (not Cancelled) and should NOT
 * expose any provider information.
 *
 * Backend marker: error_message starts with "Target met" on cancelled runs
 * generated by the over-delivery / target-met guard in execute-all-runs.
 */

export interface RunLike {
  status?: string | null;
  error_message?: string | null;
}

const TARGET_MET_PREFIX = 'target met';

export function isTargetMetAutoCompleted(run: RunLike | null | undefined): boolean {
  if (!run) return false;
  const status = (run.status || '').toString().toLowerCase().trim();
  const message = (run.error_message || '').toString().toLowerCase().trim();
  return (status === 'cancelled' || status === 'canceled') &&
    message.startsWith(TARGET_MET_PREFIX);
}

/** Returns the status to display in the UI (Completed instead of Cancelled when target was met). */
export function getUserFacingRunStatus(run: RunLike | null | undefined): string {
  const raw = (run?.status || '').toString().toLowerCase().trim();
  if (isTargetMetAutoCompleted(run)) return 'completed';
  return raw;
}

/** True if this run should be counted as delivered (real complete OR auto-completed). */
export function countsAsDelivered(run: RunLike | null | undefined): boolean {
  const raw = (run?.status || '').toString().toLowerCase().trim();
  return raw === 'completed' || isTargetMetAutoCompleted(run);
}
